### ISSUE TITLE
Application crashes`~/.ibridges` does not exist since the logger cannot write

### ISSUE THREAD

**Issue by chStaiger** [chStaiger/iBridges-Gui#133]
**Describe the bug**
If the `~/.ibridges` does not exist the logger cannot create and write to the iBridges.log file

**To Reproduce**
Make sure to NOT to have an `~/.ibridges` folder and start the app.

**Expected behavior**
Create the folder  if it does not exist

** Error message
```
% ./iBridges.py
Traceback (most recent call last):
  File "/Users/andera/git/iBridges-Gui/./iBridges.py", line 243, in <module>
    main()
  File "/Users/andera/git/iBridges-Gui/./iBridges.py", line 224, in main
    utils.utils.init_logger(THIS_APPLICATION)
  File "/Users/andera/git/iBridges-Gui/utils/utils.py", line 323, in init_logger
    file_handler = logging.handlers.RotatingFileHandler(logfile, 'a', 100000, 1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andera/miniconda3/envs/ibridges/lib/python3.11/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/Users/andera/miniconda3/envs/ibridges/lib/python3.11/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/Users/andera/miniconda3/envs/ibridges/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/Users/andera/miniconda3/envs/ibridges/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/andera/.ibridges/iBridges.log'
```

**Comment by chStaiger** [comment]
Solved by https://github.com/chStaiger/iBridges-Gui/pull/134 in develop.
