### ISSUE TITLE
Sync crashes after calculating differences

### ISSUE THREAD

**Issue by chStaiger** [chStaiger/iBridges-Gui#213]
1. Select your hom
2. Select an iRODS collection
3. calculate differences

The sync thread is closed properly, so the sync dry-run seems to work, but then it crashes with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ibridgesgui/sync.py", line 281, in _sync_diff_end
    ] + [
  File "/usr/local/lib/python3.9/site-packages/ibridgesgui/sync.py", line 282, in <listcomp>
    (lpath, ipath, lpath.stat().st_size)
  File "/usr/local/Cellar/python@3.9/3.9.18_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/christine/Library/Application Support/Google/Chrome/RunningChromeVersion'
zsh: abort      ibridges-gui
```

**Comment by chStaiger** [comment]
This is due to broken symlinks and will be fixed in the next version of iBridges
